---
title: "Package Usage"
description: >
  Package Usage
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Package Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
  - pdf/R-validation.pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE)
```

The `rqualify` package consists of 2 functions and an R Markdown file:

1. `rqualify`: Orchestrates the qualification process.
2. `rqualify_setup`: Set-ups the environment for the qualification process.
3. `R-validation.Rmd`: An R Markdown file that defines the structure and content of the PDF report.


## rqualify()

The `rqualify` function is the main function of the package, which orchestrates 
the entire qualification process. It performs the following steps sequentially:

1. Normalizes the folder path provided in `path_save`.
2. Checks for the existence of the `tests` folder in the R installation path. If the folder does not exist, an error is thrown, and the function stops execution. This check ensures that the R installation is complete and includes the necessary components for testing.
3. Calls the `rqualify_setup` function to set up the environment for the qualification process.
4. Copies the `R-validation.Rmd` file to the `R-validation` folder created
   during the setup process.
5. Renders the `R-validation.Rmd` file to a PDF report, which includes
   the results of both IQ and OQ checks.

For step 2 to be successful, R must be installed with the tests folder. This
is default behavior in Windows, but may not be the case in Linux or macOS. If you are running on 
Linux and encounter an error at this step, please refer to the instructions provided 
in the R Installation and Administration manual (https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Testing-a-Unix_002dalike-Installation) 
to install R with the tests folder.

For additional details on inputs and outputs of the `rqualify` function, please refer to the function documentation `?rqualify`.


## rqualify_setup()

The `rqualify_setup` function is called internally by the `rqualify` function,
but we make it available in the namespace. The function carries out the following
steps sequentially:

1. Creates a folder tree `R-validation/IQ-OQ-TestOutput` at the `path_save`.
2. Sets the locale and langauge settings to "C" and "en", respectively.
3. (Optional) Installs tinytex and adds it to the system path. In this step, the TinyTeX LaTeX bundle and the `grfext` LaTeX package are installed to ensure that the PDF report can be generated without errors.
4. (Optional) Installs Pandoc if not available and installs it.

During step 3, the installation of tinytex, the process may be slow and appear to
hang. This is not unexpected behavior, and the function will only proceed to the next step once the 
installation is complete.

We have also received reports from macOS users that a permissions popup may appear prompting
users to approve installation. This may occur during the stage of installing tinytex or
Pandoc. If you encounter this popup, please approve the installation to allow the process to continue. 
If you do not approve the installation, the process will not be able to proceed and will likely result in an error.

For additional details on inputs and outputs of the `rqualify_setup` function, please refer to the function documentation `?rqualify_setup`.


## Rvalidation.Rmd

The Rvalidation.Rmd file is an R Markdown file that defines the structure and content of the PDF report generated by the `rqualify` function. It includes sections for both Installation Qualification (IQ) and Operational Qualification (OQ), as well as a summary table of the checks performed and their outcomes. The file uses R code chunks to execute the necessary checks and capture any errors that occur during the process. The results of the checks are displayed in the PDF report, along with any error messages encountered during execution.

The structure of Rvalidation.Rmd closely follows [R-IQ-OQ](https://github.com/marcschwartz/R-IQ-OQ),
which is written R/Sweave. The R code chunks in Rvalidation.Rmd are adapted from the R-IQ-OQ code, with modifications to fit the structure of an R Markdown file and to capture errors for display in the PDF report.

For additional details and to see an example of a successful qualification, see `vignette("details")`.
